"""Work out how to read a cinema's schedule from one URL (ARCHITECTURE §5.7).

    detection = detect_site(url, venue)

1. SiteProbe looks at the URL and the home page (scraper/probe.py) — at most 12 requests, 2 s apart.
2. Every adapter's detect() runs in DETECT_ORDER and proposes a Candidate (adapter + parameters).
   Nothing found and no showtimes visible → a few common schedule paths are tried, then detection reruns.
3. Each candidate is run for real once (fetch + parse + the same validate() as scraper.run); the one with
   the most upcoming screenings wins, ties going to the lower DETECT_ORDER.
4. No candidate works:
     showtimes visible in the HTML          → a recipe: Claude writes one if a key is configured
                                              (scraper/recipe_gen.py), else status needs_agent
     no showtimes, but a browser shows some → needs_agent (recipe with render: browser)
     firewall challenge                     → blocked
     nothing                                → no_showtimes (probably not the schedule page)

Result statuses: ok | needs_agent | blocked | no_showtimes — the wizard and the Issue workflow turn
them into plain-language next steps.
"""
from __future__ import annotations

import copy
import logging
import re
from collections import Counter
from dataclasses import dataclass, field
from datetime import date

from .adapters import Candidate, detectable_adapters
from .base import browser_disabled, dedupe
from .models import RawPage, Screening, VenueConfig, VenueStatus
from .normalize import now_utc_iso
from .probe import TIME_TOKEN, SiteProbe, visible_text

log = logging.getLogger(__name__)

# state -> IANA zone (the zone of most of the state; the wizard lets the user override)
STATE_TZ = {
    **dict.fromkeys("CT DE DC FL GA ME MD MA MI NH NJ NY NC OH PA RI SC VT VA WV".split(), "America/New_York"),
    "IN": "America/Indiana/Indianapolis", "KY": "America/New_York",
    **dict.fromkeys("AL AR IL IA KS LA MN MS MO NE ND OK SD TN TX WI".split(), "America/Chicago"),
    **dict.fromkeys("CO MT NM UT WY".split(), "America/Denver"), "ID": "America/Boise", "AZ": "America/Phoenix",
    **dict.fromkeys("CA NV OR WA".split(), "America/Los_Angeles"),
    "AK": "America/Anchorage", "HI": "Pacific/Honolulu", "PR": "America/Puerto_Rico",
}
STATE_NAMES = {
    "New York": "NY", "Pennsylvania": "PA", "Massachusetts": "MA", "Illinois": "IL", "California": "CA",
    "Texas": "TX", "Washington": "WA", "Oregon": "OR", "Florida": "FL", "Minnesota": "MN", "Tennessee": "TN",
    "Georgia": "GA", "Colorado": "CO", "Michigan": "MI", "Ohio": "OH", "Maryland": "MD", "Arizona": "AZ",
    "Louisiana": "LA", "North Carolina": "NC", "Wisconsin": "WI", "Missouri": "MO", "Utah": "UT",
}
# "Brooklyn, NY 11249" / "Brookline, MA" at the end of an address line
ADDRESS = re.compile(r"[A-Za-z.]\s*,\s*([A-Z]{2})(?:\s+\d{5}(?:-\d{4})?\b|\s*(?=$|\n|\s{2,}|[|·•]))", re.M)


@dataclass
class Trial:
    candidate: Candidate
    screenings: list[Screening] = field(default_factory=list)   # validated (the window scraper.run keeps)
    pages: list[RawPage] = field(default_factory=list)
    error: str | None = None

    @property
    def future(self) -> int:
        return len(self.screenings)


@dataclass
class Detection:
    status: str                              # ok | needs_agent | blocked | no_showtimes
    reason: str                              # a message key suffix, see scraper/add.py MESSAGES
    probe: SiteProbe
    candidates: list[Candidate] = field(default_factory=list)
    trials: list[Trial] = field(default_factory=list)
    best: Trial | None = None
    recipe: dict | None = None               # generated by Claude, when that path succeeded
    recipe_rounds: list[dict] = field(default_factory=list)
    needs_browser: bool = False
    browser_html: str | None = None
    timezone: str | None = None
    state: str | None = None

    def evidence(self) -> dict:
        return {
            "status": self.status, "reason": self.reason,
            "probe": self.probe.evidence(),
            "candidates": [{"adapter": c.adapter, "params": c.params, "evidence": c.evidence} for c in self.candidates],
            "trials": [{"adapter": t.candidate.adapter, "upcoming": t.future, "error": t.error} for t in self.trials],
            "chosen": self.best.candidate.source if self.best else None,
            "needs_browser": self.needs_browser, "timezone_guess": self.timezone, "state_guess": self.state,
            "recipe_rounds": [{k: v for k, v in r.items() if k != "recipe_yaml"} for r in self.recipe_rounds],
        }


# ------------------------------------------------------------------ helpers
def _states_in(text: str) -> list[str]:
    return [code for code in ADDRESS.findall(text or "") if code in STATE_TZ]


def guess_state(probe: SiteProbe) -> str | None:
    """US state from the site's own address: JSON-LD PostalAddress (addressRegion, or 'City, ST 12345'
    inside streetAddress / addressLocality), then 'City, ST 12345' / 'City, ST' lines in the page text.
    State names in running text are not used — film blurbs mention New York everywhere."""
    votes: Counter = Counter()
    for obj in probe.jsonld():
        addr = obj.get("address") if isinstance(obj.get("address"), dict) else obj if "PostalAddress" in str(obj.get("@type")) else None
        if not addr:
            continue
        region = addr.get("addressRegion")
        if isinstance(region, str):
            region = region.strip()
            code = region.upper() if len(region) == 2 else STATE_NAMES.get(region)
            if code in STATE_TZ:
                votes[code] += 3
        joined = ", ".join(str(addr.get(k) or "") for k in ("streetAddress", "addressLocality", "postalCode"))
        for code in _states_in(joined):
            votes[code] += 3
    for r in probe.pages[:3]:
        for code in _states_in(visible_text(r.text)):
            votes[code] += 1
    return votes.most_common(1)[0][0] if votes else None


def page_of(resp) -> RawPage:
    return RawPage(url=resp.final_url or resp.url, body=resp.text, fetched_at=now_utc_iso(),
                   ext="json" if resp.is_json else "html")


def schedule_pages(probe: SiteProbe) -> list[RawPage]:
    """The fetched HTML pages, most showtime tokens first (what a recipe would be written against)."""
    ranked = sorted(probe.pages, key=lambda r: -r.time_tokens)
    return [page_of(r) for r in ranked if r.time_tokens][:2]


def trial(candidate: Candidate, venue: VenueConfig, client=None, today: date | None = None) -> Trial:
    from .registry import build_scraper
    from .run import validate
    v = copy.deepcopy(venue)
    v.source = candidate.source
    t = Trial(candidate)
    scraper = build_scraper(v, client=client)
    try:
        t.pages = scraper.fetch()
        rows = dedupe(scraper.parse(t.pages))
        kept, status = validate(v, rows, VenueStatus(v.id, "ok"), None, today=today)
        t.screenings = kept if status.status == "ok" else []
        if status.status != "ok":
            t.error = status.error
    except Exception as e:  # noqa: BLE001 — a failing candidate is evidence, not a crash
        t.error = f"{type(e).__name__}: {str(e)[:300]}"
    finally:
        scraper.close()
    return t


def run_detectors(probe: SiteProbe) -> list[Candidate]:
    found = []
    for cls in detectable_adapters():
        try:
            c = cls.detect(probe)
        except Exception as e:  # noqa: BLE001
            probe.log.append(f"{cls.adapter_name}.detect failed: {type(e).__name__}: {e}")
            continue
        if c is not None:
            found.append(c)
    return found


def render_with_browser(url: str, tz: str) -> str | None:
    """HTML after JavaScript, or None when no browser is available here (CI, the cloud sandbox)."""
    if browser_disabled():
        return None
    try:
        from .base import BrowserSession
        session = BrowserSession(headless=True, timezone_id=tz)
        try:
            return session.get_html(url)[1]
        finally:
            session.close()
    except Exception as e:  # noqa: BLE001 — no Playwright / no Chromium / challenge
        log.info("browser render unavailable: %s", e)
        return None


# ------------------------------------------------------------------ the whole flow
def detect_site(url: str, venue: VenueConfig, *, probe: SiteProbe | None = None, client=None,
                use_llm: bool | None = None, llm_client=None, render=render_with_browser,
                today: date | None = None) -> Detection:
    probe = probe or SiteProbe(url)
    probe.start()
    state = guess_state(probe)
    tz = STATE_TZ.get(state) if state else None

    if probe.blocked and not probe.pages:
        return Detection("blocked", probe.blocked, probe, state=state, timezone=tz)

    candidates = run_detectors(probe)
    if not candidates and probe.time_tokens == 0:
        probe.explore()
        candidates = run_detectors(probe)
        state = state or guess_state(probe)
        tz = tz or (STATE_TZ.get(state) if state else None)

    d = Detection("no_showtimes", "no_times", probe, candidates=candidates, state=state, timezone=tz)
    for c in sorted(candidates, key=lambda c: c.order):
        d.trials.append(trial(c, venue, client=client, today=today))
    good = [t for t in d.trials if t.future > 0]
    if good:
        d.best = max(good, key=lambda t: (t.future, -t.candidate.order))
        d.status, d.reason = "ok", "adapter"
        return d

    pages = schedule_pages(probe)
    if not pages and render is not None and probe.main is not None:
        html = render(probe.main.final_url or probe.main.url, venue.timezone)
        if html and len(TIME_TOKEN.findall(visible_text(html))):
            d.needs_browser, d.browser_html = True, html
            pages = [RawPage(url=probe.main.final_url or probe.main.url, body=html, fetched_at=now_utc_iso())]

    if pages:
        from . import recipe_gen
        if use_llm is None:
            use_llm = recipe_gen.available()
        if use_llm:
            gen = recipe_gen.generate(venue.name, pages[0].url, pages, venue.id, venue.timezone,
                                      horizon_days=venue.horizon_days, client=llm_client)
            d.recipe_rounds = gen.rounds
            if gen.recipe is not None:
                if d.needs_browser:
                    for p in gen.recipe.get("pages") or []:
                        p["render"] = "browser"
                d.recipe = gen.recipe
                c = Candidate("recipe", {"recipe": venue.id}, ["recipe written by Claude and checked on the page"])
                from .run import validate
                kept, _ = validate(venue, dedupe(gen.verdict.screenings), VenueStatus(venue.id, "ok"), None, today=today)
                d.best = Trial(c, kept, pages)
                d.status, d.reason = "ok", "recipe"
                return d
            d.status, d.reason = "needs_agent", "llm_failed"
            return d
        d.status = "needs_agent"
        d.reason = "browser_recipe" if d.needs_browser else "recipe"
        return d

    if probe.blocked:
        d.status, d.reason = "blocked", probe.blocked
    elif probe.main is None:
        d.reason = "unreachable"
    return d
